/** @format */
import "./globals.css";

import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import SessionProvider from "@/components/SessionProviders";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { ThemeProvider } from "@/components/ThemeProvider";
import { toast } from "sonner";
import Nofications from "@/components/Nofications";

const inter = Kanit({
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Stock Management",
    description: "Generated by create next app"
};

export default async function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession(authOptions)
    return (
        <html lang="en" suppressHydrationWarning>
            <head></head>
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem>
                    <SessionProvider session={session}>
                        {children}
                        <Toaster />
                    </SessionProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
